### ISSUE TITLE
SmartEnum with static readonly field named System causes error

### ISSUE THREAD

**Issue by djek-sweng** [PawelGerr/Thinktecture.Runtime.Extensions#4]
Hi Pawel,

implementing your SmartEnum with static readonly field named System causes error:

'MySmartEnum' does not contain a definition for 'StringComparer' and no accessible extension method 'StringComparer' accepting a first argument of type 'MySmartEnum' could be found (are you missing a using directive or an assembly reference?)

```
using Thinktecture;

namespace MyNamespace;

public partial class MySmartEnum : IEnum<string>
{
   public static readonly MySmartEnum System = new("System");
   public static readonly MySmartEnum User = new("User");
}
```

In the generated source file MySmartEnum_Generated.cs arises a conflict between System.StringComparer and the field named System.

I am using Thinktecture.Runtime.Extensions v4.0.1.

Best regards,
David

**Comment by PawelGerr** [comment]
The types are fully qualified now. Please update to v 4.1.0.
