### ISSUE TITLE
Remove explicit system.text.json dependency

### ISSUE THREAD

**Issue by thompson-tomo** [PawelGerr/Thinktecture.Runtime.Extensions#7]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework.

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by PawelGerr** [comment]
I assume you've installed [Thinktecture.Runtime.Extensions.Json](https://www.nuget.org/packages/Thinktecture.Runtime.Extensions.Json/).

If you don't need support for `System.Text.Json` then please install [Thinktecture.Runtime.Extensions](https://www.nuget.org/packages/Thinktecture.Runtime.Extensions/).

**Comment by thompson-tomo** [comment]
That is correct but key thing is that Thinktecture.Runtime.Extensions.Json doesn't need to have an explicit dependency on System.Text.Json due to the fact that is natively provided by the framework.

**Comment by PawelGerr** [comment]
I removed the explicit dependency in [7.2.1](https://github.com/PawelGerr/Thinktecture.Runtime.Extensions/releases/tag/7.2.1).
Nuget packages should be ready in 5-10min.

**Comment by thompson-tomo** [comment]
Thanks. Implementation done via https://github.com/PawelGerr/Thinktecture.Runtime.Extensions/commit/be6253d3bdcc9980d018e68a37f0dad6472e34a5
